#pragma once

#define TASK_STACK_SIZE 4096

#define MOTION_CONTROL_PRIORITY 50
#define LIDAR_COMMUNICATION_PRIORITY 49
#define TRIGGER_TIMER_PRIORITY 21
#define LUA_PRIORITY 20
#define LOGGER_PRIORITY 15
#define OTA_REBOOT_PRIORITY 14
