M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date dim. 26 févr. 2023 16:43:32
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-26T16:43:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.1Y-0.1
X0.1Y-2.5
X2.7Y-0.1
X2.7Y-2.5
T0
M30
