M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date lun. 10 juil. 2023 22:14:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-10T22:14:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.9055
X1.6535Y0.0
X1.6535Y-0.9055
T0
M30
