M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date lun. 12 juin 2023 22:03:47
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-12T22:03:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.9055
X1.6535Y0.0
X1.6535Y-0.9055
T0
M30
